name: grpc-gw
ver: 1.0.0
loglevel: 7
pprof: 9698
mailaddr: ["zhangguodong@163.com"]
# slb健康检测的ip都是以100开头的,用户的不会有这种ip,以此来过滤ws和tcp连接时的错误日志,http不影响
# !!!!如果slb的ip变的话,此处也需要修改
healthcheckip: []
consul:
  address: http://127.0.0.1:8500
  token:
  healthtype: http
  healthport: 30100
mempool:
  type: atom #('sync', 'atom' or 'chan')."
  factor: 2
  minChunk: 64
  maxChunk: 65536
  pageSize: 1048576
endpoint:
  authsvr:
    name: AuthSvr
    address: consul:///authsvr
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
  brosvr:
    name: BroSvr
    address: consul:///brosvr
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
  teamsvr:
    name: TeamSvr
    address: consul:///teamsvr
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
rpc:
  name: grpc-gw
  port: 17050
  secure: false
  certfiles:
    - cert: cert.pem
      priv: priv.key
      ca: ca.pem
servelist:
  - name: gw_tcp
    type: tcp # 0:http 1:tcp 2:ws
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
    buffersize: 30000
    maxconn: 10000
    idletimeout: 90s
    sendchansize: 1024
    recvchansize: 1024
    port: 10001
  - name: gw_ws
    type: ws # 0:http 1:tcp 2:ws
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
    buffersize: 30000
    maxconn: 10000
    idletimeout: 90s
    sendchansize: 1024
    recvchansize: 1024
    port: 10002
  - name: gw_http
    type: http # 0:http 1:tcp 2:ws
    buffersize: 30000
    maxconn: 10000
    idletimeout: 15s
    sendchansize: 1024
    recvchansize: 1024
    port: 10003
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
